import { Hadith } from '@/types/database'

// Fallback hadith data when database is empty
export const fallbackDailyHadith: Hadith[] = [
  {
    id: 'fallback-1',
    hadith_number: '১',
    book_id: 'fallback-book-1',
    category_id: 'fallback-category-1',
    chapter_arabic: 'بدء الوحي',
    chapter_bangla: 'ওহীর সূচনা',
    chapter_english: 'Beginning of Revelation',
    text_arabic: 'إِنَّمَا الْأَعْمَالُ بِالنِّيَّاتِ وَإِنَّمَا لِكُلِّ امْرِئٍ مَا نَوَى',
    text_bangla: 'নিশ্চয়ই সকল কাজ নিয়তের উপর নির্ভরশীল এবং প্রত্যেক ব্যক্তি তার নিয়ত অনুযায়ী ফল পাবে।',
    text_english: 'Actions are but by intention and every man shall have but that which he intended.',
    narrator: 'উমর ইবনুল খাত্তাব (রা.)',
    grade: 'সহীহ',
    reference: 'সহীহ বুখারী, হাদিস নং ১',
    explanation: 'এই হাদিসটি ইসলামের মৌলিক নীতিমালার একটি। যেকোনো কাজের সওয়াব বা গুনাহ নির্ভর করে নিয়তের উপর।',
    difficulty_level: 'beginner' as const,
    status: 'verified' as const,
    view_count: 0,
    like_count: 0,
    share_count: 0,
    is_featured: true,
    is_daily_special: true,
    created_at: new Date().toISOString(),
    updated_at: new Date().toISOString(),
    book: {
      id: 'fallback-book-1',
      name_arabic: 'صحيح البخاري',
      name_bangla: 'সহীহ বুখারী',
      name_english: 'Sahih al-Bukhari',
      author_bangla: 'ইমাম বুখারী (রহ.)',
      author_arabic: 'الإمام البخاري',
      author_english: 'Imam al-Bukhari',
      description: 'হাদিসের সবচেয়ে নির্ভরযোগ্য সংকলন',
      total_hadith: 7563,
      is_active: true,
      created_at: new Date().toISOString()
    },
    category: {
      id: 'fallback-category-1',
      name_bangla: 'ঈমান ও আকীদা',
      name_arabic: 'الإيمان والعقيدة',
      name_english: 'Faith and Belief',
      description: 'ইসলামী বিশ্বাস ও আকীদা সংক্রান্ত হাদিস',
      icon: '🕌',
      color: '#10B981',
      sort_order: 1,
      is_active: true,
      created_at: new Date().toISOString()
    }
  },
  {
    id: 'fallback-2',
    hadith_number: '৬০১৮',
    book_id: 'fallback-book-1',
    category_id: 'fallback-category-2',
    chapter_arabic: 'الأدب',
    chapter_bangla: 'আদব',
    chapter_english: 'Good Manners',
    text_arabic: 'مَنْ كَانَ يُؤْمِنُ بِاللَّهِ وَالْيَوْمِ الْآخِرِ فَلْيَقُلْ خَيْرًا أَوْ لِيَصْمُتْ',
    text_bangla: 'যে ব্যক্তি আল্লাহ ও আখিরাতে বিশ্বাস রাখে, সে যেন ভালো কথা বলে অথবা চুপ থাকে।',
    text_english: 'Whoever believes in Allah and the Last Day should speak good or keep silent.',
    narrator: 'আবু হুরায়রা (রা.)',
    grade: 'সহীহ',
    reference: 'সহীহ বুখারী, হাদিস নং ৬০১৮',
    explanation: 'এই হাদিস আমাদের কথাবার্তায় সতর্কতা অবলম্বনের শিক্ষা দেয়। ভালো কথা না বলতে পারলে চুপ থাকাই উত্তম।',
    difficulty_level: 'beginner' as const,
    status: 'verified' as const,
    view_count: 0,
    like_count: 0,
    share_count: 0,
    is_featured: true,
    is_daily_special: true,
    created_at: new Date().toISOString(),
    updated_at: new Date().toISOString(),
    book: {
      id: 'fallback-book-1',
      name_arabic: 'صحيح البخاري',
      name_bangla: 'সহীহ বুখারী',
      name_english: 'Sahih al-Bukhari',
      author_bangla: 'ইমাম বুখারী (রহ.)',
      author_arabic: 'الإمام البخاري',
      author_english: 'Imam al-Bukhari',
      description: 'হাদিসের সবচেয়ে নির্ভরযোগ্য সংকলন',
      total_hadith: 7563,
      is_active: true,
      created_at: new Date().toISOString()
    },
    category: {
      id: 'fallback-category-2',
      name_bangla: 'আখলাক ও চরিত্র',
      name_arabic: 'الأخلاق والآداب',
      name_english: 'Morals and Ethics',
      description: 'নৈতিকতা ও চরিত্র গঠনের হাদিস',
      icon: '❤️',
      color: '#EC4899',
      sort_order: 2,
      is_active: true,
      created_at: new Date().toISOString()
    }
  },
  {
    id: 'fallback-3',
    hadith_number: '৪৮১',
    book_id: 'fallback-book-1',
    category_id: 'fallback-category-3',
    chapter_arabic: 'الصلاة',
    chapter_bangla: 'সালাত',
    chapter_english: 'Prayer',
    text_arabic: 'الْمُؤْمِنُ لِلْمُؤْمِنِ كَالْبُنْيَانِ يَشُدُّ بَعْضُهُ بَعْضًا',
    text_bangla: 'মুমিন মুমিনের জন্য প্রাচীরের মতো, যার এক অংশ অপর অংশকে মজবুত রাখে।',
    text_english: 'The believer to another believer is like a building whose different parts enforce each other.',
    narrator: 'আবু মুসা (রা.)',
    grade: 'সহীহ',
    reference: 'সহীহ বুখারী, হাদিস নং ৪৮১',
    explanation: 'এই হাদিস মুসলিম উম্মাহর একতা ও পারস্পরিক সহযোগিতার গুরুত্ব তুলে ধরে।',
    difficulty_level: 'beginner' as const,
    status: 'verified' as const,
    view_count: 0,
    like_count: 0,
    share_count: 0,
    is_featured: true,
    is_daily_special: true,
    created_at: new Date().toISOString(),
    updated_at: new Date().toISOString(),
    book: {
      id: 'fallback-book-1',
      name_arabic: 'صحيح البخاري',
      name_bangla: 'সহীহ বুখারী',
      name_english: 'Sahih al-Bukhari',
      author_bangla: 'ইমাম বুখারী (রহ.)',
      author_arabic: 'الإمام البخاري',
      author_english: 'Imam al-Bukhari',
      description: 'হাদিসের সবচেয়ে নির্ভরযোগ্য সংকলন',
      total_hadith: 7563,
      is_active: true,
      created_at: new Date().toISOString()
    },
    category: {
      id: 'fallback-category-3',
      name_bangla: 'নামাজ',
      name_arabic: 'الصلاة',
      name_english: 'Prayer',
      description: 'নামাজ ও ইবাদত সংক্রান্ত হাদিস',
      icon: '🤲',
      color: '#3B82F6',
      sort_order: 3,
      is_active: true,
      created_at: new Date().toISOString()
    }
  }
]
